spring:
  application:
    name: spring-batch-redis

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-batch-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
server:
  port: 8095
